#!/usr/bin/env python
# coding: UTF-8
from django.utils.translation import ugettext as _
#global COUNTRIES

COUNTRIES = (
    ('BR',     _(u'Brasil') ), 
    ('AF',     _(u'Afeganistão') ), 
    ('ZA',     _(u'África do Sul') ), 
    ('AX',     _(u'Åland, Ilhas') ), 
    ('AL',     _(u'Albânia') ), 
    ('DE',     _(u'Alemanha') ), 
    ('AD',     _(u'Andorra') ), 
    ('AO',     _(u'Angola') ), 
    ('AI',     _(u'Anguilla') ), 
    ('AQ',     _(u'Antárctida') ), 
    ('AG',     _(u'Antígua e Barbuda') ), 
    ('AN',     _(u'Antilhas Holandesas') ), 
    ('SA',     _(u'Arábia Saudita') ), 
    ('DZ',     _(u'Argélia') ), 
    ('AR',     _(u'Argentina') ), 
    ('AM',     _(u'Armênia') ), 
    ('AW',     _(u'Aruba') ), 
    ('AU',     _(u'Austrália') ), 
    ('AT',     _(u'Áustria') ), 
    ('AZ',     _(u'Azerbaijão') ), 
    ('BS',     _(u'Bahamas') ), 
    ('BH',     _(u'Bahrain') ), 
    ('BD',     _(u'Bangladesh') ), 
    ('BB',     _(u'Barbados') ), 
    ('BE',     _(u'Bélgica') ), 
    ('BZ',     _(u'Belize') ), 
    ('BJ',     _(u'Benim') ), 
    ('BM',     _(u'Bermudas') ), 
    ('BY',     _(u'Bielorrússia') ), 
    ('BO',     _(u'Bolívia') ), 
    ('BA',     _(u'Bósnia e Herzegovina') ), 
    ('BW',     _(u'Botswana') ), 
    ('BV',     _(u'Bouvet, Ilha') ), 
    ('BN',     _(u'Brunei') ), 
    ('BG',     _(u'Bulgária') ), 
    ('BF',     _(u'Burkina Faso') ), 
    ('BI',     _(u'Burundi') ), 
    ('BT',     _(u'Butão') ), 
    ('CV',     _(u'Cabo Verde') ), 
    ('KH',     _(u'Cambodja') ), 
    ('CM',     _(u'Camarões') ), 
    ('CA',     _(u'Canadá') ), 
    ('KY',     _(u'Cayman, Ilhas') ), 
    ('KZ',     _(u'Cazaquistão') ), 
    ('CF',     _(u'Centro-Africana, República') ), 
    ('TD',     _(u'Chade') ), 
    ('CZ',     _(u'Checa, República') ), 
    ('CL',     _(u'Chile') ), 
    ('CN',     _(u'China') ), 
    ('CY',     _(u'Chipre') ), 
    ('CX',     _(u'Christmas, Ilha') ), 
    ('CC',     _(u'Cocos, Ilhas') ), 
    ('CO',     _(u'Colômbia') ), 
    ('KM',     _(u'Comores') ), 
    ('CG',     _(u'Congo, República do') ), 
    ('CD',     _(u'Congo, República Democrática do (antigo Zaire)') ), 
    ('CK',     _(u'Cook, Ilhas') ), 
    ('KR',     _(u'Coréia do Sul') ), 
    ('KP',     _(u'Coreia, República Democrática da (Coreia do Norte)') ), 
    ('CI',     _(u'Costa do Marfim') ), 
    ('CR',     _(u'Costa Rica') ), 
    ('HR',     _(u'Croácia') ), 
    ('CU',     _(u'Cuba') ), 
    ('DK',     _(u'Dinamarca') ), 
    ('DJ',     _(u'Djibouti') ), 
    ('DM',     _(u'Dominica') ), 
    ('DO',     _(u'Dominicana, República') ), 
    ('EG',     _(u'Egito') ), 
    ('SV',     _(u'El Salvador') ), 
    ('AE',     _(u'Emirados Árabes Unidos') ), 
    ('EC',     _(u'Equador') ), 
    ('ER',     _(u'Eritreia') ), 
    ('SK',     _(u'Eslováquia') ), 
    ('SI',     _(u'Eslovênia') ), 
    ('ES',     _(u'Espanha') ), 
    ('US',     _(u'Estados Unidos da América') ), 
    ('EE',     _(u'Estónia') ), 
    ('ET',     _(u'Etiópia') ), 
    ('FO',     _(u'Feroé, Ilhas') ), 
    ('FJ',     _(u'Fiji') ), 
    ('PH',     _(u'Filipinas') ), 
    ('FI',     _(u'Finlândia') ), 
    ('FR',     _(u'França') ), 
    ('GA',     _(u'Gabão') ), 
    ('GM',     _(u'Gâmbia') ), 
    ('GH',     _(u'Gana') ), 
    ('GE',     _(u'Geórgia') ), 
    ('GS',     _(u'Geórgia do Sul e Sandwich do Sul, Ilhas') ), 
    ('GI',     _(u'Gibraltar') ), 
    ('GR',     _(u'Grécia') ), 
    ('GD',     _(u'Grenada') ), 
    ('GL',     _(u'Groenlândia') ), 
    ('GP',     _(u'Guadalupe') ), 
    ('GU',     _(u'Guam') ), 
    ('GT',     _(u'Guatemala') ), 
    ('GG',     _(u'Guernsey') ), 
    ('GY',     _(u'Guiana') ), 
    ('GF',     _(u'Guiana Francesa') ), 
    ('GW',     _(u'Guiné-Bissau') ), 
    ('GN',     _(u'Guiné-Conacri') ), 
    ('GQ',     _(u'Guiné Equatorial') ), 
    ('HT',     _(u'Haiti') ), 
    ('HM',     _(u'Heard e Ilhas McDonald, Ilha') ), 
    ('HN',     _(u'Honduras') ), 
    ('HK',     _(u'Hong Kong') ), 
    ('HU',     _(u'Hungria') ), 
    ('YE',     _(u'Iémen') ), 
    ('IN',     _(u'Índia') ), 
    ('ID',     _(u'Indonésia') ), 
    ('IQ',     _(u'Iraque') ), 
    ('IR',     _(u'Irã') ), 
    ('IE',     _(u'Irlanda') ), 
    ('IS',     _(u'Islândia') ), 
    ('IL',     _(u'Israel') ), 
    ('IT',     _(u'Itália') ), 
    ('JM',     _(u'Jamaica') ), 
    ('JP',     _(u'Japão') ), 
    ('JE',     _(u'Jersey') ), 
    ('JO',     _(u'Jordânia') ), 
    ('KI',     _(u'Kiribati') ), 
    ('KW',     _(u'Kuwait') ), 
    ('LA',     _(u'Laos') ), 
    ('LS',     _(u'Lesoto') ), 
    ('LV',     _(u'Letônia') ), 
    ('LB',     _(u'Líbano') ), 
    ('LR',     _(u'Libéria') ), 
    ('LY',     _(u'Líbia') ), 
    ('LI',     _(u'Liechtenstein') ), 
    ('LT',     _(u'Lituânia') ), 
    ('LU',     _(u'Luxemburgo') ), 
    ('MO',     _(u'Macau') ), 
    ('MK',     _(u'Macedônia, República da') ), 
    ('MG',     _(u'Madagáscar') ), 
    ('MY',     _(u'Malásia') ), 
    ('MW',     _(u'Malawi') ), 
    ('MV',     _(u'Maldivas') ), 
    ('ML',     _(u'Mali') ), 
    ('MT',     _(u'Malta') ), 
    ('FK',     _(u'Malvinas, Ilhas (Falkland)') ), 
    ('IM',     _(u'Man, Ilha de') ), 
    ('MP',     _(u'Marianas Setentrionais') ), 
    ('MA',     _(u'Marrocos') ), 
    ('MH',     _(u'Marshall, Ilhas') ), 
    ('MQ',     _(u'Martinica') ), 
    ('MU',     _(u'Maurícia') ), 
    ('MR',     _(u'Mauritânia') ), 
    ('YT',     _(u'Mayotte') ), 
    ('UM',     _(u'Menores Distantes dos Estados Unidos, Ilhas') ), 
    ('MX',     _(u'México') ), 
    ('MM',     _(u'Myanmar (antiga Birmânia)') ), 
    ('FM',     _(u'Micronésia, Estados Federados da') ), 
    ('MZ',     _(u'Moçambique') ), 
    ('MD',     _(u'Moldávia') ), 
    ('MC',     _(u'Mônaco') ), 
    ('MN',     _(u'Mongólia') ), 
    ('ME',     _(u'Montenegro') ), 
    ('MS',     _(u'Montserrat') ), 
    ('NA',     _(u'Namíbia') ), 
    ('NR',     _(u'Nauru') ), 
    ('NP',     _(u'Nepal') ), 
    ('NI',     _(u'Nicarágua') ), 
    ('NE',     _(u'Níger') ), 
    ('NG',     _(u'Nigéria') ), 
    ('NU',     _(u'Niue') ), 
    ('NF',     _(u'Norfolk, Ilha') ), 
    ('NO',     _(u'Noruega') ), 
    ('NC',     _(u'Nova Caledônia') ), 
    ('NZ',     _(u'Nova Zelândia (Aotearoa)') ), 
    ('OM',     _(u'Oman') ), 
    ('NL',     _(u'Países Baixos (Holanda)') ), 
    ('PW',     _(u'Palau') ), 
    ('PS',     _(u'Palestina') ), 
    ('PA',     _(u'Panamá') ), 
    ('PG',     _(u'Papua-Nova Guiné') ), 
    ('PK',     _(u'Paquistão') ), 
    ('PY',     _(u'Paraguai') ), 
    ('PE',     _(u'Peru') ), 
    ('PN',     _(u'Pitcairn') ), 
    ('PF',     _(u'Polinésia Francesa') ), 
    ('PL',     _(u'Polônia') ), 
    ('PR',     _(u'Porto Rico') ), 
    ('PT',     _(u'Portugal') ), 
    ('QA',     _(u'Qatar') ), 
    ('KE',     _(u'Quênia') ), 
    ('KG',     _(u'Quirguistão') ), 
    ('GB',     _(u'Reino Unido da Grã-Bretanha e Irlanda do Norte') ), 
    ('RE',     _(u'Reunião') ), 
    ('RO',     _(u'Romênia') ), 
    ('RW',     _(u'Ruanda') ), 
    ('RU',     _(u'Rússia') ), 
    ('EH',     _(u'Saara Ocidental') ), 
    ('AS',     _(u'Samoa Americana') ), 
    ('WS',     _(u'Samoa (Samoa Ocidental)') ), 
    ('PM',     _(u'Saint Pierre et Miquelon') ), 
    ('SB',     _(u'Salomão, Ilhas') ), 
    ('KN',     _(u'São Cristóvão e Névis (Saint Kitts e Nevis)') ), 
    ('SM',     _(u'San Marino') ), 
    ('ST',     _(u'São Tomé e Príncipe') ), 
    ('VC',     _(u'São Vicente e Granadinas') ), 
    ('SH',     _(u'Santa Helena') ), 
    ('LC',     _(u'Santa Lúcia') ), 
    ('SN',     _(u'Senegal') ), 
    ('SL',     _(u'Serra Leoa') ), 
    ('RS',     _(u'Sérvia') ), 
    ('SC',     _(u'Seychelles') ), 
    ('SG',     _(u'Singapura') ), 
    ('SY',     _(u'Síria') ), 
    ('SO',     _(u'Somália') ), 
    ('LK',     _(u'Sri Lanka') ), 
    ('SZ',     _(u'Suazilândia') ), 
    ('SD',     _(u'Sudão') ), 
    ('SE',     _(u'Suécia') ), 
    ('CH',     _(u'Suíça') ), 
    ('SR',     _(u'Suriname') ), 
    ('SJ',     _(u'Svalbard e Jan Mayen') ), 
    ('TH',     _(u'Tailândia') ), 
    ('TW',     _(u'Taiwan') ), 
    ('TJ',     _(u'Tajiquistão') ), 
    ('TZ',     _(u'Tanzânia') ), 
    ('TF',     _(u'Terras Austrais e Antárticas Francesas (TAAF)') ), 
    ('IO',     _(u'Território Britânico do Oceano Índico') ), 
    ('TL',     _(u'Timor-Leste') ), 
    ('TG',     _(u'Togo') ), 
    ('TK',     _(u'Toquelau') ), 
    ('TO',     _(u'Tonga') ), 
    ('TT',     _(u'Trindade e Tobago') ), 
    ('TN',     _(u'Tunísia') ), 
    ('TC',     _(u'Turks e Caicos') ), 
    ('TM',     _(u'Turquemenistão') ), 
    ('TR',     _(u'Turquia') ), 
    ('TV',     _(u'Tuvalu') ), 
    ('UA',     _(u'Ucrânia') ), 
    ('UG',     _(u'Uganda') ), 
    ('UY',     _(u'Uruguai') ), 
    ('UZ',     _(u'Usbequistão') ), 
    ('VU',     _(u'Vanuatu') ), 
    ('VA',     _(u'Vaticano') ), 
    ('VE',     _(u'Venezuela') ), 
    ('VN',     _(u'Vietnam') ), 
    ('VI',     _(u'Virgens Americanas, Ilhas') ), 
    ('VG',     _(u'Virgens Britânicas, Ilhas') ), 
    ('WF',     _(u'Wallis e Futuna') ), 
    ('ZM',     _(u'Zâmbia') ), 
    ('ZW',     _(u'Zimbabwe') ),
    ('  ',     _(u'Outro') )
)


BRSTATES = (
    ('AC', _(u'Acre') ),
    ('AL', _(u'Alagoas') ),
    ('AP', _(u'Amapá') ),
    ('AM', _(u'Amazonas') ),
    ('BA', _(u'Bahia') ),
    ('CE', _(u'Ceará') ),
    ('DF', _(u'Distrito Federal') ),
    ('ES', _(u'Espírito Santo') ),
    ('GO', _(u'Goiás') ),
    ('MA', _(u'Maranhão') ),
    ('MT', _(u'Mato Grosso') ),
    ('MS', _(u'Mato Grosso do Sul') ),
    ('MG', _(u'Minas Gerais') ),
    ('PA', _(u'Pará') ),
    ('PB', _(u'Paraíba') ),
    ('PR', _(u'Paraná') ),
    ('PE', _(u'Pernambuco') ),
    ('PI', _(u'Piauí') ),
    ('RJ', _(u'Rio de Janeiro') ),
    ('RN', _(u'Rio Grande do Norte') ),
    ('RS', _(u'Rio Grande do Sul') ),
    ('RO', _(u'Rondônia') ),
    ('RR', _(u'Roraima') ),
    ('SC', _(u'Santa Catarina') ),
    ('SP', _(u'São Paulo') ),
    ('SE', _(u'Sergipe') ),
    ('TO', _(u'Tocantins') ),
    ('  ', _(u'Outro') ),
)


ADDRESS_TYPES = (
    ('W', _(u'Endereço de Trabalho')),
    ('H', _(u'Endereço Residencial')),
    ('O', _(u'Endereço de Origem ')),
)


RELATIONS = (
    ('IC', _(u'Graduação - Iniciação Científica')),
    ('GI', _(u'Graduação - Intercâmbio')),
    ('GM', _(u'Graduação - Monitoria')),
    ('MS', _(u'Mestrado')),
    ('DT', _(u'Doutorado')),
    ('PD', _(u'Pós Doutorado')),
    ('AP', _(u'Aluno Especial')),
    ('P', _(u'Docente')),
    ('V', _(u'Visitante')),
    ('F', _(u'Funcionário')),
    ('E', _(u'Estagiário')),
    ('IU', _(u'Interunidades')),
    ('O', _(u'Outros')),
)

GENDERS = (
    ('M', _(u'Masculino')),
    ('F', _(u'Feminino')),
    )

MARITAL_STATUS = (
    ('I', _(u'Solteiro')),
    ('C', _(u'Casado')),
    ('S', _(u'Separado')),
    ('D', _(u'Divorciado')),
    ('V', _(u'Viúvo')),
)


DEDICATION = (
    ('I', _(u'Tempo Integral')),
    ('P', _(u'Tempo Parcial')),
)


OCCURENCES = (
    ('MS_mat', _(u'Matrícula Mestrado')),
    ('DT_mat', _(u'Matrícula Doutorado')),
    ('POS_PAE', _(u'Programa PAE')),
    ('POS_EProf', _(u'Exame de Proficiência')),
    ('MS_quali', _(u'Qualificação Mestrado')),
    ('DT_quali', _(u'Qualificação Doutorado')),
    ('MS_def', _(u'Defesa Mestrado')),
    ('DT_def', _(u'Defesa Doutorado')),
    ('PD_mat', _(u'Matrícula Pós-Doutorado')),
    ('POS_OrIC', _(u'Orientação Iniciação Científica')),
    ('POS_OrTr', _(u'Cadastro e Troca de Orientador/Co-Orientador')),
    ('POS_Bolsa', _(u'Cadastro e Troca de Órgão Financiador')),
    ('POS_EExt', _(u'Estágio no Exterior')),
    ('G_Outras', _(u'Outras Ocorrências')),
    ('POS_APDisc', _(u'Disciplina Aluno Especial')),
    ('POS_Conc', _(u'Conclusão')),
    ('G_Desl', _(u'Desligamento')),
)

